# Experimentos aleatorizados — Clase empírica {#experimentos-aleatorizados-clase-empirica}

## Materiales para la clase {-}

::: {.class-materials}
**Descarga antes de comenzar**

- **[Participar en el experimento de vocabulario (estudiantes)](https://experimento-vocabulario-clase6.web.app/)**
- [Do-file de Stata](https://raw.githubusercontent.com/adiazescobar/libro_cortes/main/dofile/06_RCT_Stata/clase6_stata.do)
- [Base `data.dta`](https://raw.githubusercontent.com/adiazescobar/libro_cortes/main/dofile/06_RCT_Stata/data.dta)
- [Script de R](https://raw.githubusercontent.com/adiazescobar/libro_cortes/main/dofile/06_RCT_Stata/clase6_R.R)
- [Notebook de Python](https://raw.githubusercontent.com/adiazescobar/libro_cortes/main/dofile/06_RCT_Stata/clase6_python.ipynb)
- [Resultados completos de Stata](https://raw.githubusercontent.com/adiazescobar/libro_cortes/main/dofile/06_RCT_Stata/results/resultados_stata.csv)
- [Verificación Stata–Python](https://raw.githubusercontent.com/adiazescobar/libro_cortes/main/dofile/06_RCT_Stata/results/verificacion_stata_python.csv)

<a class="colab-link" href="https://colab.research.google.com/github/adiazescobar/libro_cortes/blob/main/dofile/06_RCT_Stata/clase6_python.ipynb" target="_blank" rel="noopener">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Abrir notebook en Google Colab">
</a>
:::

::: {.box-stata}
**Objetivos de la práctica**

En el capítulo anterior formalizamos la teoría de resultados potenciales, la descomposición del sesgo de selección, su conexión con el sesgo por variable omitida, y los **cuatro escenarios de diseño** experimental. Ahora implementamos todo esto paso a paso en Stata, usando datos reales de un experimento de aula replicado en cuatro semestres.

- Implementar los **cuatro escenarios de regresión** (simple, con controles, estratificado, estratificado + controles).
- Ejecutar **diagnósticos de balance**, **efectos heterogéneos** y el **truco de centrar** de Wooldridge.
- Manejar **inferencia estadística** (SE robustas, clusters, bootstrap).
- Producir **reporte reproducible** exportable a Excel/PDF.

### Lecturas {-}

- **Paper Alert:** [When Should You Adjust Standard Errors for Clustering? (NBER w24003)](https://www.nber.org/papers/w24003)
- **Teoría:** [Jakiela & Ozier — Handout](http://economics.ozier.com/econ626/lec/econ626-L07-handout-2019.pdf)
- **Herramienta:** [J-PAL — Power calculations](https://www.povertyactionlab.org/resource/power-calculations)
:::

::: {.boxinfo}
**Lecturas centrales**

- [Bernal y Peña — capítulo 4 (PDF)](https://www.dropbox.com/s/vxpgxt22pvphwx3/Capitulo%204%20Bernal%20y%20Pe%C3%B1a.pdf?dl=1)
- [Cunningham — capítulo 4: Potential Outcomes](https://mixtape.scunning.com/04-potential_outcomes)
:::



## Pregunta empírica {-}

¿Cuál es el efecto causal de recibir definiciones de palabras difíciles, en lugar de un texto crítico de economía, sobre el resultado de un quiz de vocabulario? Además de estimar el efecto promedio, evaluaremos si respetar los estratos del diseño y agregar controles pretratamiento cambia la precisión.

## Datos {-}

La práctica usa una única base congelada, `data.dta`, con 70 observaciones provenientes de un experimento de aula replicado en cuatro semestres. El grupo B recibió las definiciones y constituye el tratamiento; el grupo A recibió el texto crítico y constituye el control. La variable `semestre` identifica los estratos de asignación.

::: {.box-cuidado}
Stata y Python deben leer exactamente esta misma base. Si el archivo no está disponible o le falta alguna variable requerida, ambos flujos se detienen: no se generan datos sustitutos.
:::


## Recordatorio teórico (del capítulo anterior) {-}

*1) Setup*

- Unidades: \(N\).
- Tratamiento: \(D_i \in \{0,1\}\). Asignado de manera aleatoria.
- Resultados potenciales: \(Y_i(D=1),\, Y_i(D=0)\).
- Resultado observado:
  \[
  Y_i \;=\; D_i\,Y_i(D=1) \;+\; (1-D_i)\,Y_i(D=0).
  \]
- Tamaños de muestra:
  - Tratados: \(N_1 = \sum_i \mathbb{1}\{D_i=1\}\).
  - Control: \(N_0 = \sum_i \mathbb{1}\{D_i=0\}\).

 *2) Supuestos*

1. **Asignación aleatoria:** cada unidad \(i\) es asignada de manera independiente al tratamiento con probabilidad \(p\).
   \[
   D_i \;\perp\; \{Y_i(D=1), Y_i(D=0)\}.
   \]
2. **SUTVA** (Stable Unit Treatment Value Assumption): no hay interferencia entre unidades ni versiones del tratamiento.
   En español: no hay externalidades ni efectos de equilibrio general que cambien los resultados potenciales de otros individuos.

*3) Parámetros y equivalencias clave*

- **ATE:** \(\tau = \mathbb{E}[Y_i(D=1)-Y_i(D=0)]\).
- **ATT:** \(\mathbb{E}[Y_i(D=1)-Y_i(D=0) \mid D_i=1]\).
- **ATU:** \(\mathbb{E}[Y_i(D=1)-Y_i(D=0) \mid D_i=0]\).

Bajo aleatorización: \(ATE = ATT = ATU\), porque los grupos son comparables en todo (observable y no observable).

- **Identificación con aleatorización:**
  \[
  \mathbb{E}[\,Y \mid D=1\,] - \mathbb{E}[\,Y \mid D=0\,] \;=\; \tau.
  \]
- **Estimador por diferencia de medias:**
  \[
  \hat{\tau} \;=\; \bar{Y}_{D=1}-\bar{Y}_{D=0}.
  \]
- **Descomposición (sin aleatorización):**
  \[
  \underbrace{\mathbb{E}[Y \mid D=1] - \mathbb{E}[Y \mid D=0]}_{\text{naïve}}
  \;=\;
  \underbrace{\tau}_{\text{efecto causal}}
  \;+\;
  \underbrace{\mathbb{E}[Y_i(D=0)\mid D_i=1] - \mathbb{E}[Y_i(D=0)\mid D_i=0]}_{\text{sesgo de selección}}.
  \]

::: {.boxnote}
**Conexión con variable omitida (cap. anterior):** en regresión, el sesgo de selección es exactamente el sesgo por variable omitida: \(\text{sesgo} = \gamma \cdot \text{Cov}(D,M)/\text{Var}(D)\). La aleatorización garantiza \(\text{Cov}(D,M)=0\) para **cualquier** variable \(M\), observable o no.
:::


## Desarrollo guiado del RCT {-}

### Pregunta, tratamiento, resultado y unidad de asignación {-}

La unidad de asignación es el estudiante. El tratamiento es recibir definiciones de palabras difíciles (grupo B), el control es recibir el texto crítico de economía (grupo A) y el resultado es el puntaje del quiz. El estimando principal es el ATE sobre los 70 estudiantes de los cuatro semestres. Antes de recolectar datos, el protocolo fija población objetivo, resultado primario, tamaño de muestra y mínima diferencia detectable.

::: {.box-intuicion}
**Interpretación:** la unidad de asignación determina qué observaciones pueden considerarse independientes y el nivel correcto de la inferencia. No debe confundirse con la unidad en la que se mide el resultado.
:::

### Inspección y preparación de los datos {-}

```stata
use "data.dta", clear
describe
gen long student_id = _n
isid student_id
assert inlist(grupo, "A", "B")
assert !missing(resultado, semestre, edad, genero, programa, libros)
gen byte D = (grupo == "B")
gen y = resultado
gen mujer = (genero == "Mujer")
gen pregrado = (programa == "Pregrado")
gen maestria = (programa == "Maestría")
global X edad mujer libros pregrado maestria
tab semestre D
```

::: {.box-stata}
**Comando clave:** `isid student_id` comprueba que cada fila representa una unidad única; los `assert` detienen el flujo si cambia el contrato de datos.
:::


### Semilla y asignación aleatoria {-}

Abajo tienes varias formas de asignar tratamiento en Stata. Incluyo opciones con `runiform()` (base) y con el comando de SSC `randtreat` (estratificado, proporciones desiguales, clusters y manejo de *misfits*).

> **Regla de oro:** fija una semilla reproducible y *guárdala* en el log/notas del proyecto.
```stata
* Reproducibilidad
set seed 20250813
local RNGSTATE = c(rngstate)   // guardar estado; opcionalmente escríbelo en tu log
display as text "Seed guardada: `RNGSTATE'"
```

La semilla reproduce la secuencia pseudoaleatoria solo si también se conserva el orden de las observaciones y el algoritmo. Por eso se ordena por un identificador estable antes de generar números. En una asignación Bernoulli, cada unidad tiene probabilidad conocida \(p\), pero el número final de tratados es aleatorio.

::: {.box-cuidado}
**Error frecuente:** fijar la semilla después de `runiform()` o reordenar la base entre ejecuciones cambia la asignación. Registrar semilla no reemplaza archivar la lista final de asignación.
:::

### Aleatorización simple y estratificada {-}

*Bernoulli simple (50/50) con `runiform()`*

Asigna tratamiento con probabilidad 0.5 a cada unidad.

```stata
sort student_id
gen double u_simple50 = runiform()
gen byte D_simple50 = (u_simple50 < 0.5)
tab D_simple50
```

**Cambio de proporción (p=0.30):**

```stata
gen double u_simple30 = runiform()
gen byte D_simple30 = (u_simple30 < 0.30)
tab D_simple30
```

**Asignación con conteo exacto de tratados (p.ej., 40% exacto)**

Asegura exactamente `round(N*0.40)` tratados.

```stata
count
local N      = r(N)
local Ntr    = round(`N'*0.40)   // número exacto de tratados
gen double u_exact40 = runiform()
sort u_exact40
gen byte D_exact40 = (_n <= `Ntr')
tab D_exact40
sort student_id
```

**Estratificada** (bloques) con `runiform()`

Mantén la proporción deseada **dentro de cada estrato** (ej., por `mujer` × `programa`).

> Con `round()` obtienes conteo **exacto por estrato**; globalmente puede variar levemente si los tamaños de estrato son impares.

```stata
egen long strata = group(mujer programa), label
bys strata: gen double u_estrato50 = runiform()
bys strata (u_estrato50): gen byte D_estrato50 = (_n <= round(_N*0.50))
tab D_estrato50
by strata: tab D_estrato50
sort student_id
```

**Proporción distinta por estrato (p.ej., 40%):**

```stata
bys strata: gen double u_estrato40 = runiform()
bys strata (u_estrato40): gen byte D_estrato40 = (_n <= round(_N*0.40))
by strata: tab D_estrato40
sort student_id
```

**Cluster** (aleatoriza a nivel del cluster y la pasa a individuos)

Ej.: clusters en `escuela`.

```stata
* Una fila por cluster
preserve
keep escuela
duplicates drop

gen double u = runiform()
sort u
* 50% de escuelas tratadas
count
local C = r(N)
local Ctr = round(`C'*0.50)
gen byte D_cluster = (_n <= `Ctr')
tempfile cl
save `cl', replace
restore

* Trae la asignación al nivel individual
merge m:1 escuela using `cl', keep(match master) nogen
tab D_cluster
```

Usando **`randtreat`** (SSC): multi-brazos, proporciones desiguales, estratos y *misfits*

**Instalación**

```stata
ssc install randtreat, replace
```

**Binario 50/50 (sin estratos)**

```stata
randtreat, generate(D_rand50) multiple(2) setseed(20250813)
tab D_rand50
```

**Binario 50/50 dentro de estratos (`mujer` × `programa`)**

```stata
randtreat, generate(D_randestrato) multiple(2) strata(mujer programa) setseed(20250813)
by mujer programa: tab D_randestrato
```

** Proporciones desiguales (30% tratado, 70% control)**

```stata
randtreat, generate(D_rand30) multiple(2) unequal(0.30 0.70) setseed(20250813)
tab D_rand30
```

** Multi-brazo (T1/T2/C = 0.4/0.4/0.2) con estratos**

```stata
randtreat, generate(arm) multiple(3) unequal(0.40 0.40 0.20) ///
    strata(mujer programa) setseed(20250813)
tab arm
by mujer programa: tab arm
```

**Manejo de *misfits***
Cuando el tamaño de estrato no es divisible por los brazos/proporciones, usa `misfits()`:

* `misfits(strata)` o `misfits(wstrata)`: resuelve dentro de cada estrato (ponderado o no).
* `misfits(global)` o `misfits(wglobal)`: resuelve a nivel global priorizando las proporciones totales.
* `misfits(missing)`: deja *misfits* sin asignar para que los decidas manualmente.

```stata
randtreat, generate(arm_misfits) multiple(3) unequal(0.40 0.40 0.20) ///
    strata(mujer programa) misfits(wstrata) setseed(20250813)
```

**Forzar número exacto de tratados totales** (binario)

> Útil si necesitas exactamente `N_t` tratados (no solo proporción).

```stata
* Por ejemplo, exactamente 50 tratados en total:
randtreat, generate(D_randexacta) multiple(2) ntreated(50) setseed(20250813)
tab D_randexacta
```

**Cluster + `randtreat`**
Ejecuta `randtreat` sobre los **clusters únicos** y luego une a individuos.

```stata
preserve
keep escuela mujer programa
duplicates drop

* 2 brazos 50/50 por estratos de escuela (y opcionalmente otras):
randtreat, generate(Dcl) multiple(2) strata(mujer programa) setseed(20250813)
tempfile cl
save `cl', replace
restore

merge m:1 escuela using `cl', nogen
tab Dcl
```

La asignación simple da a cada estudiante la misma probabilidad marginal. La estratificada preserva la proporción dentro de grupos definidos antes del tratamiento y debe analizarse incorporando esos estratos. Diferencias basales pueden aparecer por azar aun con una asignación correcta: son balance fortuito, no prueba automática de manipulación.

::: {.box-resultado}
**Resultado clave:** el protocolo elige simple o estratificada antes de observar resultados. Realeatorizar porque una covariable “salió significativa” altera la distribución de asignación y exige documentar esa regla.
:::

### Tabla de balance {-}

Aquí vamos a **Verificar el balance de covariables** con resultados exportados por Stata, no con cifras transcritas.

Nuestra base `data.dta` contiene datos de un experimento de aula replicado en **cuatro semestres**. En cada semestre, a un grupo se le entregaron **definiciones de palabras difíciles** (tratamiento) y al otro un **texto crítico de economía** (control), y luego todos presentaron el mismo quiz de vocabulario.

```stata
use "data.dta", clear

* Tratamiento 1=B (definiciones), 0=A (texto crítico)
gen D = (grupo == "B")
label define Dlbl 0 "Control" 1 "Tratado"
label values D Dlbl

* Outcome y controles
gen y        = resultado
gen mujer    = (genero == "Mujer")
gen pregrado = (programa == "Pregrado")
gen maestria = (programa == "Maestría")

* Semestre como estrato (variable clave para escenarios 3 y 4)
tab semestre D

global X edad mujer libros pregrado maestria
```
* Programa de diferencia de medias con t-test y opción de guardar resultados en un archivo .dta**

1. **Pruebas univariadas (t‐tests):** comparar medias de cada covariable \(X\) entre \(D=1\) y \(D=0\).  
   Objetivo: **no rechazar** que las medias son iguales.
2. **Prueba conjunta (F‐test):** regresión de \(D\) sobre \(X\) (LPM) y test conjunto de significancia de \(X\).
3. **Modelos binarios:** `logit/probit` de \(D\) sobre \(X\); evaluar razón de verosimilitud o \(\chi^2\) conjunta.
4. **Si se rechaza balance:** revisar procedimiento (bloqueos/estratos, reasignación, control por \(X\) pretratamiento en la estimación).

```stata
cap program drop difmedias
program define difmedias, rclass
    version 18
    syntax varlist(min=1) [, BY(varname) SAVEPOST(string asis)]
    if ("`by'"=="") {
        di as err "Necesitas especificar , by(varname)."
        exit 198
    }
    local vars `varlist'

    local do_post = 0
    if ("`savepost'"!="") local do_post = 1
    tempname posth
    if `do_post' {
        postfile `posth' str32 variable ///
            double mean_T mean_C diff tstat pval se sd_T sd_C N_T N_C ///
            using "`savepost'", replace
    }

    di as txt "Var{col 22}Mean_T{col 33}Mean_C{col 44}Diff{col 55}t{col 66}p"
    foreach v of local vars {
        qui ttest `v', by(`by')

        local mu1 = r(mu_1)
        local mu2 = r(mu_2)
        local sd1 = r(sd_1)
        local sd2 = r(sd_2)
        local N1  = r(N_1)
        local N2  = r(N_2)
        local t   = r(t)
        local se  = r(se)
        local p   = r(p)

        local mean_T = `mu2'
        local mean_C = `mu1'
        local diff   = `mu2' - `mu1'

        di as res "`v'" "{col 22}" %9.3f `mean_T' "{col 33}" %9.3f `mean_C' "{col 44}" %9.3f `diff' "{col 55}" %9.3f `t' "{col 66}" %9.3f `p'

        if `do_post' {
            post `posth' ("`v'") (`mean_T') (`mean_C') (`diff') (`t') (`p') (`se') (`sd2') (`sd1') (`N2') (`N1')
        }
    }
    if `do_post' postclose `posth'
end


* Balance de X
difmedias $X, by(D) savepost("Table_Balance_raw.dta")

use "Table_Balance_raw.dta", clear
order variable mean_T mean_C diff tstat pval se sd_T sd_C N_T N_C
export excel using "Table_Balance_raw.xlsx", firstrow(variables) replace

* ALTERNATIVAS 
cap which iebaltab
if _rc ssc install ietoolkit, replace

iebaltab $X, grpvar(D) control(0) rowvarlabels ftest ///
     savexlsx("Table_Balance.xlsx") replace format(%9.3f)

eststo clear
eststo: reg   D $X, vce(robust)
test $X
eststo: logit D $X, vce(robust)
eststo: probit D $X, vce(robust)

esttab, se star(* 0.10 ** 0.05 *** 0.01) ///
    stats(N r2, fmt(%9.0g %9.3f) labels("N" "R2")) ///
    nomtitle compress

```

**Resultados del balance (con nuestros datos):**

**Balance de covariables — resultados de Stata**

<table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Variable </th>
   <th style="text-align:right;"> Media tratados </th>
   <th style="text-align:right;"> Media control </th>
   <th style="text-align:right;"> Diferencia </th>
   <th style="text-align:right;"> p-valor </th>
   <th style="text-align:right;"> N tratados </th>
   <th style="text-align:right;"> N control </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> edad </td>
   <td style="text-align:right;"> 26.513 </td>
   <td style="text-align:right;"> 23.548 </td>
   <td style="text-align:right;"> 2.964 </td>
   <td style="text-align:right;"> 0.095 </td>
   <td style="text-align:right;"> 39 </td>
   <td style="text-align:right;"> 31 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> mujer </td>
   <td style="text-align:right;"> 0.282 </td>
   <td style="text-align:right;"> 0.258 </td>
   <td style="text-align:right;"> 0.024 </td>
   <td style="text-align:right;"> 0.826 </td>
   <td style="text-align:right;"> 39 </td>
   <td style="text-align:right;"> 31 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> libros </td>
   <td style="text-align:right;"> 3.674 </td>
   <td style="text-align:right;"> 2.726 </td>
   <td style="text-align:right;"> 0.949 </td>
   <td style="text-align:right;"> 0.264 </td>
   <td style="text-align:right;"> 39 </td>
   <td style="text-align:right;"> 31 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> pregrado </td>
   <td style="text-align:right;"> 0.513 </td>
   <td style="text-align:right;"> 0.355 </td>
   <td style="text-align:right;"> 0.158 </td>
   <td style="text-align:right;"> 0.191 </td>
   <td style="text-align:right;"> 39 </td>
   <td style="text-align:right;"> 31 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> maestria </td>
   <td style="text-align:right;"> 0.487 </td>
   <td style="text-align:right;"> 0.645 </td>
   <td style="text-align:right;"> -0.158 </td>
   <td style="text-align:right;"> 0.191 </td>
   <td style="text-align:right;"> 39 </td>
   <td style="text-align:right;"> 31 </td>
  </tr>
</tbody>
</table>

Las diferencias son las medias de tratados menos las de control. La tabla permite evaluar tanto su magnitud como su precisión; el balance no debe juzgarse únicamente variable por variable, por lo que complementamos esta lectura con la prueba conjunta.

Además del p-valor, conviene reportar la diferencia estandarizada: diferencia de medias dividida por una desviación estándar combinada. Esta medida separa magnitud de tamaño muestral. Un p-valor grande no demuestra igualdad y, con muchas pruebas, algún p-valor pequeño puede aparecer por azar. Ante desbalance fortuito se conserva la asignación, se documenta y se ajusta por covariables pretratamiento o por la regla prespecificada.

::: {.box-salida}
**Salida central:** la tabla canónica presenta medias por brazo, diferencia, p-valor y tamaños de grupo para cada covariable; se lee junto con magnitudes sustantivas y el protocolo.
:::

### Prueba conjunta de balance {-}



**Prueba conjunta (LPM):** F = 3.249, p-valor = 0.017. Se rechaza balance conjunto.

::: {.box-interpretacion}
**Interpretación:** en `reg D $X, vce(robust)` y `test $X`, la hipótesis conjunta es que las covariables no predicen la asignación. No rechazar no prueba aleatoriedad; la evidencia principal sigue siendo el mecanismo documentado.
:::

::: {.box-ejercicio}
**RCT-S1 — Aleatorización y balance**

Una base contiene 70 estudiantes, identificados por `student_id`, distribuidos en cuatro valores de `semestre`. Use la semilla `20250813`. Formule y ejecute dos asignaciones: Bernoulli simple con `p=0.50` y conteo 50/50 dentro de cada `semestre`. Para la asignación estratificada, evalúe balance de `edad`, `mujer` y `libros` con pruebas individuales y con una prueba conjunta `D ~ X`. ¿Qué elementos conservaría para que otra persona reproduzca la asignación? ¿Cómo distinguiría desbalance fortuito de un error de implementación?

**Puntaje sugerido:** 5 puntos.

**Comandos permitidos:** `sort`, `generate`, `isid`, `set seed`, `runiform()`, `bysort`, `tabulate`, `list`, `ttest`, `reg`, `test`.

**Producto esperado:** dos listas de asignación reproducibles, tabla de balance individual, prueba conjunta y evaluación escrita del balance fortuito.
:::

### RCT simple sin controles {-}

En el capítulo anterior derivamos **los cuatro escenarios** según el diseño experimental. Ahora los implementamos en Stata, usando `semestre` como variable de estrato \(S_i\):

::: {.table .table-bordered .table-striped}
| Escenario | Regresión | Objetivo |
|:---:|:---|:---|
| 1 | \( Y_i = \alpha + \tau D_i + u_i \) | Identificación pura por aleatorización |
| 2 | \( Y_i = \alpha + \tau D_i + \beta' X_i + u_i \) | + precisión con controles baseline |
| 3 | \( Y_i = \alpha + \tau D_i + \delta' S_i + u_i \) | Respetar diseño estratificado |
| 4 | \( Y_i = \alpha + \tau D_i + \delta' S_i + \beta' X_i + u_i \) | Diseño + eficiencia (especificación completa) |
:::

Con probabilidades de tratamiento iguales entre estratos y una especificación compatible con el diseño, los cuatro coeficientes apuntan al mismo ATE de la población objetivo; los controles pretratamiento y estratos pueden cambiar la precisión. Si las probabilidades difieren entre estratos o los efectos son heterogéneos, la regresión no ponderada puede inducir una ponderación distinta de la población objetivo. En ese caso se debe prespecificar el estimando y usar ponderación por la población objetivo o un promedio explícito de efectos por estrato.

```stata
* ── Escenario 1: RCT simple (diferencia de medias) ──────────────────────
eststo clear
eststo m1: reg y D, vce(robust)
```

El coeficiente de `D` coincide con la diferencia de medias. `vce(robust)` permite varianzas distintas entre brazos.

### RCT simple con controles {-}

```stata
* ── Escenario 2: RCT simple + controles baseline ────────────────────────
eststo m2: reg y D $X, vce(robust)
```

Los controles pretratamiento no crean identificación; pueden reducir la varianza residual si predicen el resultado.

### RCT estratificado sin controles adicionales {-}

```stata
* ── Escenario 3: Estratificado por semestre, sin controles ───────────────
eststo m3: reg y D i.semestre, vce(robust)
```

Las dummies de `semestre` incorporan los bloques usados por el diseño y comparan estudiantes dentro de cohortes.

### RCT estratificado con controles adicionales {-}

```stata
* ── Escenario 4: Estratificado + controles (especificación completa) ────
eststo m4: reg y D i.semestre $X, vce(robust)
```

Esta especificación combina la estructura de asignación con covariables basales predictivas.

### Comparación de las cuatro especificaciones {-}

```stata
* Comparar los cuatro modelos lado a lado
esttab m1 m2 m3 m4, se star(* 0.10 ** 0.05 *** 0.01) ///
    stats(N r2, fmt(%9.0g %9.3f) labels("N" "R2")) ///
    b(%9.4f) compress nonote ///
    mtitle("Simple" "+Controles" "+Estratos" "Completo") ///
    title("Cuatro escenarios de estimación del ATE")
```

**Resultados (con nuestros datos):**

**Cuatro escenarios de estimación del ATE — resultados de Stata**

<table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Modelo </th>
   <th style="text-align:right;"> ATE estimado </th>
   <th style="text-align:right;"> Error estándar robusto </th>
   <th style="text-align:right;"> IC 95% inferior </th>
   <th style="text-align:right;"> IC 95% superior </th>
   <th style="text-align:right;"> gl residuales </th>
   <th style="text-align:right;"> N </th>
   <th style="text-align:right;"> R² </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Simple </td>
   <td style="text-align:right;"> 4.312 </td>
   <td style="text-align:right;"> 0.476 </td>
   <td style="text-align:right;"> 3.362 </td>
   <td style="text-align:right;"> 5.262 </td>
   <td style="text-align:right;"> 68 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 0.553 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Con controles </td>
   <td style="text-align:right;"> 4.252 </td>
   <td style="text-align:right;"> 0.464 </td>
   <td style="text-align:right;"> 3.324 </td>
   <td style="text-align:right;"> 5.180 </td>
   <td style="text-align:right;"> 63 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 0.593 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Con estratos </td>
   <td style="text-align:right;"> 4.390 </td>
   <td style="text-align:right;"> 0.429 </td>
   <td style="text-align:right;"> 3.533 </td>
   <td style="text-align:right;"> 5.248 </td>
   <td style="text-align:right;"> 65 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 0.650 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Completo </td>
   <td style="text-align:right;"> 4.296 </td>
   <td style="text-align:right;"> 0.440 </td>
   <td style="text-align:right;"> 3.415 </td>
   <td style="text-align:right;"> 5.177 </td>
   <td style="text-align:right;"> 60 </td>
   <td style="text-align:right;"> 70 </td>
   <td style="text-align:right;"> 0.672 </td>
  </tr>
</tbody>
</table>

::: {.boxnote}
**Observe cómo cambian los SE de \(\hat{\tau}\)** entre los cuatro modelos. El punto estimado debe ser similar (la aleatorización garantiza consistencia), pero los errores estándar se reducen al agregar variables que predicen \(Y\). Los estratos (semestre) absorben diferencias de nivel entre cohortes.
:::

::: {.box-ejercicio}
**RCT-S2 — Lectura de modelos y precisión**

Sobre la muestra canónica de 70 estudiantes se obtienen: Simple: coeficiente 4.312, SE 0.476, gl 68; Con controles: coeficiente 4.252, SE 0.464, gl 63; Con estratos: coeficiente 4.390, SE 0.429, gl 65; Completo: coeficiente 4.296, SE 0.440, gl 60. Compare coeficientes, precisión e IC 95% con referencia t y los grados de libertad residuales indicados. ¿Cuál especificación es más precisa en esta muestra? Justifique por qué una SE menor no significa que los controles hayan creado la identificación y explique qué condición de ponderación permite interpretar las cuatro columnas como el mismo ATE objetivo.

**Puntaje sugerido:** 5 puntos.

**Comandos permitidos:** `display invttail(gl, 0.025)` para obtener cada valor crítico t; calculadora básica para multiplicar y sumar.

**Producto esperado:** cálculos de cuatro IC 95% y una comparación argumentada de estimando, precisión y ponderación.
:::
::: {.boxnote}
Interpretación según escala de \(Y\)

1. **\(Y\) en niveles (continuo):** \(\hat{\tau}\) es diferencia de unidades de \(Y\) entre tratados y control.
2. **\(Y\) en logaritmos:** \(\hat{\tau}\) es una **semi-elasticidad**; el efecto porcentual aproximado es \(100\times \hat{\tau}\%\).
   Efecto exacto: \(100\times(\exp(\hat{\tau})-1)\%\).
   *Ejemplo:* \(\hat{\tau}=0.13 \Rightarrow \exp(0.13)-1 \approx 0.139\) → **13.9%**.
3. **\(Y\) estandarizado:** media 0 y varianza 1; \(\hat{\tau}\) se interpreta en **desviaciones estándar**.
4. **\(Y\) binario:** \(\hat{\tau}\) es **diferencia de probabilidades** (puntos porcentuales).
   *Ejemplo:* \(p_1=0.30\), \(p_0=0.25\) ⇒ \(\hat{\tau}=0.05 = 5\) pp.
:::



### Inferencia y unidad de asignación {-}

###  Asignación a nivel individual (dos muestras independientes) {-}
- **Varianza del estimador (clásica):**
  \[
  \operatorname{Var}(\hat{\tau})
  \;\approx\;
  \frac{S_1^2}{N_1} \;+\; \frac{S_0^2}{N_0},
  \]
  donde \(S_1^2\) y \(S_0^2\) son las varianzas muestrales por grupo.
- **Heterocedasticidad:** usar **SE robustas** (HC).  
- **Asignación por clusters:** usar **SE cluster** al nivel de asignación. Con pocos clusters, considerar **wild cluster bootstrap**.

Con asignación individual, HC1 es coherente con independencia entre estudiantes. Si se asignaran escuelas o salones, `vce(cluster escuela)` debe reflejar esa unidad, porque los resultados dentro del cluster pueden estar correlacionados. Con pocos clusters, la aproximación asintótica y sus grados de libertad son frágiles; se reporta el número de clusters y se considera inferencia aleatorizada o wild cluster bootstrap.

### Pruebas {-}
- **Significancia individual:** \(H_0:\,\tau=0\) (t‐test).  
- **Significancia conjunta de \(X\):** en \(D \sim X\), \(H_0:\,\beta_X=0\) (F/\(\chi^2\)). Queremos **no rechazar**.

### Cuándo incluir controles {-}

- **Identificación:** con aleatorización correcta, **no necesitas** \(X\) para identificar \(\tau\).
- **Precisión:** incluir \(X\) **pretratamiento** que **expliquen \(Y\)** puede **reducir** \(\operatorname{Var}(\hat{\tau})\) (menor varianza residual).  
  Si \(X\) es irrelevante o colineal, puede **aumentar** la SE de \(\hat{\tau}\).
- **Modelo con controles:**
  \[
  Y_i \;=\; \alpha + \tau D_i + X_i'\beta + u_i.
  \]
  Si \(X \perp D\) (por diseño) y \(X\) explica \(Y\), esperar **SE(D)** más pequeñas.

Los controles deben medirse antes del tratamiento. Un control postratamiento puede ser mediador o colisionador: condicionarlo cambia el estimando y puede introducir sesgo. La regla de selección y la especificación principal se fijan antes de mirar impactos.

::: {.box-cuidado}
**Error frecuente:** añadir asistencia posterior al tratamiento “para mejorar el ajuste” puede bloquear parte del efecto causal. Un R² mayor no garantiza una estimación causal más válida.
:::

::: {.box-ejercicio}
**RCT-S3 — Inferencia y controles**

Diseño A asigna individualmente a 240 estudiantes dentro de salones. Diseño B asigna tratamiento a 24 escuelas y mide a 20 estudiantes por escuela. Para ambos se observan puntaje basal, género, asistencia posterior al tratamiento y puntaje final. Decida el nivel de los errores estándar en cada diseño y si usaría cada covariable como control principal. Explique qué cambia con solo 24 clusters y por qué la asistencia posterior requiere un tratamiento distinto de las covariables basales.

**Puntaje sugerido:** 5 puntos.

**Comandos permitidos:** `reg`, `vce(robust)`, `vce(cluster ...)`, `test`.

**Producto esperado:** dos especificaciones de inferencia y una clasificación razonada de las cuatro covariables.
:::

### Heterogeneidad mediante interacciones {-}

Los **Efectos heterogéneos (HET)** permiten preguntar si el impacto cambia con características basales.

- **Especificación general:**
  \[
  Y_i \;=\; \alpha \;+\; \tau D_i \;+\; \gamma W_i \;+\; \delta\, (D_i \times W_i) \;+\; X_i'\beta \;+\; u_i,
  \]
  donde \(W\) es el moderador (p. ej., **mujer**, **libros**, **cuartiles de edad**).
- **Interpretación:** \(\delta\) es el **cambio en el efecto de \(D\)** al pasar de un nivel de \(W\) a otro.
  Usar `margins`/`marginsplot` para reportar efectos marginales y perfiles por subgrupo. `margins, dydx(D)` entrega cambios tratados-control (CATE); otros comandos de `margins` pueden entregar niveles predichos y no deben rotularse como efectos.

```stata
* Por mujer (binaria)
eststo clear
eststo: reg y i.D##i.mujer, vce(robust)
margins, dydx(D)
margins D#mujer

* Por libros (continua)
eststo: reg y i.D##c.libros, vce(robust)
margins, dydx(D) at(libros=(0(1)8))
marginsplot, title("Efecto marginal de D según libros")
graph export "margins_libros.pdf", replace

* Por cuartiles de edad
xtile q_edad = edad, nq(4)
eststo: reg y i.D##i.q_edad, vce(robust)
margins D#q_edad
marginsplot, title("Heterogeneidad por cuartiles de edad")
graph export "margins_qedad.pdf", replace
```

### Efecto base y CATE {-}

Para una moderadora binaria, el coeficiente de `D` es el efecto base cuando \(W=0\); el CATE cuando \(W=1\) es la suma del coeficiente de `D` y el de la interacción. Para libros o edad, el CATE cambia con el valor del moderador. `lincom` y `margins, dydx(D)` calculan esa combinación con su error estándar.

```stata
reg y i.D##i.mujer, vce(robust)
lincom 1.D + 1.D#1.mujer
margins mujer, dydx(D)

reg y i.D##c.libros, vce(robust)
margins, dydx(D) at(libros=(0(1)8))
```

**Resultados (con nuestros datos):**

**Heterogeneidad por género — resultado principal de Stata**

<table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Moderador </th>
   <th style="text-align:left;"> Término </th>
   <th style="text-align:right;"> Coeficiente </th>
   <th style="text-align:right;"> Error estándar robusto </th>
   <th style="text-align:right;"> N </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Género </td>
   <td style="text-align:left;"> Tratamiento × Mujer </td>
   <td style="text-align:right;"> 0.984 </td>
   <td style="text-align:right;"> 1.059 </td>
   <td style="text-align:right;"> 70 </td>
  </tr>
</tbody>
</table>

La interacción es positiva, pero su error estándar es grande en relación con la magnitud estimada. En esta muestra no hay evidencia precisa de que el efecto difiera por género; el gráfico siguiente ayuda a leer los niveles predichos sin convertir una estimación imprecisa en una conclusión de heterogeneidad.

<img src="06-RCT2_files/figure-html/het-mujer-1.png" width="768" />

<img src="06-RCT2_files/figure-html/het-edad-1.png" width="576" />

### Centrado de covariables {-}

**El truco de centrar (Wooldridge)**

En el capítulo anterior vimos que si interactuamos \(D\) con una covariable \(W\), el coeficiente \(\tau\) es el efecto ajustado para \(W=0\). Al centrar la covariable, ese coeficiente pasa a ser el efecto ajustado en la media de \(W\):

\[
W_c = W - \bar{W}, \qquad Y_i = \alpha + \tau D_i + \gamma W_{c,i} + \delta (D_i \cdot W_{c,i}) + u_i
\]

Como \(\mathbb{E}[W_c]=0\), el coeficiente de tratamiento se evalúa en \(W=\bar W\). Solo coincide con el ATE bajo una forma funcional adecuada y una agregación compatible con la población objetivo. En general, el ATE ajustado se obtiene como el promedio de los CATE predichos para las unidades, con los pesos del diseño correspondientes.

```stata
* ── Sin centrar: τ = efecto solo para libros=0 ──────────────────────────
reg y i.D##c.libros, vce(robust)

* ── Con centrado: efecto ajustado en libros = media ─────────────────────
sum libros
gen libros_c = libros - r(mean)
reg y i.D##c.libros_c, vce(robust)
* Para un promedio ajustado, promediar CATE predichos con pesos de diseño
```

**Resultados (con nuestros datos):**


```{=html}
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_vc4lzbqd8a52jecjf0ma = TinyTable.createTableFunctions("tinytable_vc4lzbqd8a52jecjf0ma");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '14', j: 2 }, { i: '14', j: 3 } ], css_id: 'tinytable_css_9kj7ts5h8s9zgvqddd1h',}, 
          { positions: [ { i: '12', j: 2 }, { i: '12', j: 3 } ], css_id: 'tinytable_css_rz0syiqzxq16mbjsuyv4',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '13', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '13', j: 3 } ], css_id: 'tinytable_css_6n332b1cgyo1pj0pytnz',}, 
          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_v34yecd74f0trs3d1jxi',}, 
          { positions: [ { i: '14', j: 1 } ], css_id: 'tinytable_css_z1lk0ii64s97xke8h5x6',}, 
          { positions: [ { i: '12', j: 1 } ], css_id: 'tinytable_css_lx1k53twovkwu5qqxmhk',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '13', j: 1 } ], css_id: 'tinytable_css_b5dhn2xxm1jl7jbd9ii3',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_g5ke9u2kcvcn4xlpamvf',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_vc4lzbqd8a52jecjf0ma.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_vc4lzbqd8a52jecjf0ma td.tinytable_css_9kj7ts5h8s9zgvqddd1h, #tinytable_vc4lzbqd8a52jecjf0ma th.tinytable_css_9kj7ts5h8s9zgvqddd1h {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_vc4lzbqd8a52jecjf0ma td.tinytable_css_rz0syiqzxq16mbjsuyv4, #tinytable_vc4lzbqd8a52jecjf0ma th.tinytable_css_rz0syiqzxq16mbjsuyv4 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_vc4lzbqd8a52jecjf0ma td.tinytable_css_6n332b1cgyo1pj0pytnz, #tinytable_vc4lzbqd8a52jecjf0ma th.tinytable_css_6n332b1cgyo1pj0pytnz { text-align: center }
    #tinytable_vc4lzbqd8a52jecjf0ma td.tinytable_css_v34yecd74f0trs3d1jxi, #tinytable_vc4lzbqd8a52jecjf0ma th.tinytable_css_v34yecd74f0trs3d1jxi {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_vc4lzbqd8a52jecjf0ma td.tinytable_css_z1lk0ii64s97xke8h5x6, #tinytable_vc4lzbqd8a52jecjf0ma th.tinytable_css_z1lk0ii64s97xke8h5x6 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_vc4lzbqd8a52jecjf0ma td.tinytable_css_lx1k53twovkwu5qqxmhk, #tinytable_vc4lzbqd8a52jecjf0ma th.tinytable_css_lx1k53twovkwu5qqxmhk {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_vc4lzbqd8a52jecjf0ma td.tinytable_css_b5dhn2xxm1jl7jbd9ii3, #tinytable_vc4lzbqd8a52jecjf0ma th.tinytable_css_b5dhn2xxm1jl7jbd9ii3 { text-align: left }
    #tinytable_vc4lzbqd8a52jecjf0ma td.tinytable_css_g5ke9u2kcvcn4xlpamvf, #tinytable_vc4lzbqd8a52jecjf0ma th.tinytable_css_g5ke9u2kcvcn4xlpamvf {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_vc4lzbqd8a52jecjf0ma" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing='true'>
        <caption>Truco de centrar: comparación</caption>
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">Sin centrar</th>
                <th scope="col" data-row="0" data-col="3">Con centrado</th>
              </tr>
        </thead>
        <tfoot><tr><td colspan='3'>* p < 0.1, ** p < 0.05, *** p < 0.01</td></tr>
<tr><td colspan='3'>Sin centrar: coef(D) = efecto cuando libros = 0.</td></tr>
<tr><td colspan='3'>Con centrado: coef(D) = efecto ajustado en la media de libros.</td></tr></tfoot>
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">(Intercept)</td>
                  <td data-row="1" data-col="2">2.927***</td>
                  <td data-row="1" data-col="3">3.438***</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1"></td>
                  <td data-row="2" data-col="2">(0.442)</td>
                  <td data-row="2" data-col="3">(0.363)</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">D (tratamiento)</td>
                  <td data-row="3" data-col="2">4.669***</td>
                  <td data-row="3" data-col="3">4.221***</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1"></td>
                  <td data-row="4" data-col="2">(0.580)</td>
                  <td data-row="4" data-col="3">(0.475)</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">libros</td>
                  <td data-row="5" data-col="2">0.157**</td>
                  <td data-row="5" data-col="3"></td>
                </tr>
                <tr>
                  <td data-row="6" data-col="1"></td>
                  <td data-row="6" data-col="2">(0.067)</td>
                  <td data-row="6" data-col="3"></td>
                </tr>
                <tr>
                  <td data-row="7" data-col="1">D x libros</td>
                  <td data-row="7" data-col="2">-0.138*</td>
                  <td data-row="7" data-col="3"></td>
                </tr>
                <tr>
                  <td data-row="8" data-col="1"></td>
                  <td data-row="8" data-col="2">(0.082)</td>
                  <td data-row="8" data-col="3"></td>
                </tr>
                <tr>
                  <td data-row="9" data-col="1">libros (centrado)</td>
                  <td data-row="9" data-col="2"></td>
                  <td data-row="9" data-col="3">0.157**</td>
                </tr>
                <tr>
                  <td data-row="10" data-col="1"></td>
                  <td data-row="10" data-col="2"></td>
                  <td data-row="10" data-col="3">(0.067)</td>
                </tr>
                <tr>
                  <td data-row="11" data-col="1">D x libros_c</td>
                  <td data-row="11" data-col="2"></td>
                  <td data-row="11" data-col="3">-0.138*</td>
                </tr>
                <tr>
                  <td data-row="12" data-col="1"></td>
                  <td data-row="12" data-col="2"></td>
                  <td data-row="12" data-col="3">(0.082)</td>
                </tr>
                <tr>
                  <td data-row="13" data-col="1">Num.Obs.</td>
                  <td data-row="13" data-col="2">70</td>
                  <td data-row="13" data-col="3">70</td>
                </tr>
                <tr>
                  <td data-row="14" data-col="1">R2</td>
                  <td data-row="14" data-col="2">0.563</td>
                  <td data-row="14" data-col="3">0.563</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
```

::: {.boxnote}
**Regla práctica:** centrar una variable continua hace interpretable el coeficiente de \(D\) en el valor medio; no reemplaza promediar CATE ni aplicar los pesos del diseño para estimar el ATE objetivo.
:::

::: {.box-ejercicio}
**RCT-S4 — Interacción, CATE y concordancia**

En un caso hipotético, tras `reg y i.D##i.mujer i.D##c.libros, vce(robust)`, el coeficiente de `1.D` es 3.20, el de `1.D#1.mujer` es 0.80 y el de `1.D#c.libros` es 0.15. Calcule el efecto ajustado para el perfil `mujer=1`, `libros=4` y escriba el `lincom` correspondiente. Después, use este **escenario hipotético de diagnóstico**: la referencia canónica de Stata para el modelo completo reporta coeficiente 4.2956, SE 0.4404 y N=70; unos valores Python deliberadamente divergentes, generados para el ejercicio, reportan 4.2156, 0.3964 y N=68. Diagnostique en orden las comprobaciones de muestra, fórmula, codificación de estratos y covarianza que haría antes de atribuir la discrepancia al software. Distinga en su reporte niveles predichos de `dydx(D)`/CATE.

**Puntaje sugerido:** 5 puntos.

**Comandos permitidos:** `reg`, `lincom`, `margins`, `summarize`, `gen`, Python `statsmodels`.

**Producto esperado:** cálculo y comando del CATE para el perfil, más un diagnóstico secuencial de la discrepancia entre lenguajes.
:::

### Replicación en Python y Colab {-}

La sección conserva la **Replicación en Python / Google Colab** del pipeline original.

::: {.box-colab}
**Google Colab:** el notebook lee la misma `data.dta`, reconstruye las mismas variables y replica los cuatro modelos con errores estándar HC1.

<a href="https://colab.research.google.com/github/adiazescobar/libro_cortes/blob/main/dofile/06_RCT_Stata/clase6_python.ipynb" target="_blank" rel="noopener">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Abrir en Colab">
</a>

[Descargar directamente el notebook](https://raw.githubusercontent.com/adiazescobar/libro_cortes/main/dofile/06_RCT_Stata/clase6_python.ipynb)
:::

El núcleo de la réplica usa las mismas definiciones y especificaciones:

```python
df["D"] = (df["grupo"] == "B").astype(int)
df["y"] = pd.to_numeric(df["resultado"], errors="coerce")

m1 = smf.ols("y ~ D", data=df).fit(cov_type="HC1")
m2 = smf.ols("y ~ D + edad + mujer + libros + pregrado + maestria", data=df).fit(cov_type="HC1")
m3 = smf.ols("y ~ D + C(semestre_f)", data=df).fit(cov_type="HC1")
m4 = smf.ols("y ~ D + C(semestre_f) + edad + mujer + libros + pregrado + maestria", data=df).fit(cov_type="HC1")
```

El mapeo exige la misma fórmula, codificación de categorías, muestra completa y covarianza HC1. `i.semestre` corresponde a `C(semestre_f)`. Si el diseño tuviera probabilidades desiguales, ambos lenguajes tendrían que usar los mismos pesos; los estratos se incluyen explícitamente en ambos. Antes de comparar se verifican N, categorías base y valores faltantes.

### Concordancia Stata–Python {-}

Esta es la **Verificación Stata vs. Python** de los cuatro modelos.

Stata y Python exportan un CSV canónico con coeficiente, error estándar, N y \(R^2\). El comparador exige diferencias absolutas menores que \(10^{-3}\) para coeficientes y errores estándar, igualdad exacta de N y diferencias menores que \(10^{-2}\) para \(R^2\).

**Verificación automática de los cuatro modelos RCT**

<table class="table table-striped table-hover" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Modelo </th>
   <th style="text-align:right;"> Coef. Stata </th>
   <th style="text-align:right;"> Coef. Python </th>
   <th style="text-align:right;"> Dif. coef. </th>
   <th style="text-align:right;"> SE Stata </th>
   <th style="text-align:right;"> SE Python </th>
   <th style="text-align:right;"> Dif. SE </th>
   <th style="text-align:center;"> N igual </th>
   <th style="text-align:center;"> Estado </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> m1_simple </td>
   <td style="text-align:right;"> 4.311828 </td>
   <td style="text-align:right;"> 4.311828 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0.476153 </td>
   <td style="text-align:right;"> 0.476153 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:center;"> True </td>
   <td style="text-align:center;"> PASS </td>
  </tr>
  <tr>
   <td style="text-align:left;"> m2_controles </td>
   <td style="text-align:right;"> 4.251850 </td>
   <td style="text-align:right;"> 4.251850 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0.464408 </td>
   <td style="text-align:right;"> 0.464408 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:center;"> True </td>
   <td style="text-align:center;"> PASS </td>
  </tr>
  <tr>
   <td style="text-align:left;"> m3_estratos </td>
   <td style="text-align:right;"> 4.390222 </td>
   <td style="text-align:right;"> 4.390222 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0.429350 </td>
   <td style="text-align:right;"> 0.429350 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:center;"> True </td>
   <td style="text-align:center;"> PASS </td>
  </tr>
  <tr>
   <td style="text-align:left;"> m4_completo </td>
   <td style="text-align:right;"> 4.295554 </td>
   <td style="text-align:right;"> 4.295554 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0.440411 </td>
   <td style="text-align:right;"> 0.440411 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:center;"> True </td>
   <td style="text-align:center;"> PASS </td>
  </tr>
</tbody>
</table>

::: {.box-verificacion}
**Criterio de publicación:** los cuatro modelos deben aparecer como `PASS`. Los p-valores se conservan en los archivos fuente, pero no forman parte del criterio porque Stata usa una referencia t finita y `statsmodels` reporta la aproximación normal para HC1.
:::

::: {.boxejercicio}
**Ejercicios adicionales**

Estas actividades amplían la práctica y no sustituyen las cuatro preguntas tipo parcial anteriores.

1. **Aleatorización (Bernoulli y estratos)**
   (a) Con tu `data.dta`, genera `D_practica50` con p=0.5 usando `runiform()`.
   (b) Genera por separado `D_practica30` con p=0.3.
   (c) Crea estratos por `mujer × programa` y guarda la asignación 50/50 exacta en `D_practica_estrato`.

2. **`randtreat` avanzado**
   (a) Asigna 3 brazos (T1/T2/C) con proporciones 0.4/0.4/0.2 y estratos `mujer × programa`.
   (b) Resuelve *misfits* con `misfits(wstrata)` y reporta conteos por estrato.

3. **Balance**
   (a) Corre `difmedias $X, by(D)` y exporta a `Table_Balance_raw.xlsx`.
   (b) Estima `D ~ X` (LPM/logit/probit) y reporta el test conjunto.
   (c) Interpreta: ¿hay evidencia de desbalance?

4. **Los cuatro escenarios**
   (a) Estima los cuatro modelos de la sección **Comparación de las cuatro especificaciones** (simple, +controles, +estratos, completo).
   (b) Compara \(\hat{\tau}\) y sus SE entre los cuatro. ¿Cuál tiene menor SE? ¿Por qué?
   (c) ¿Cambia mucho el punto estimado al incluir estratos? Discute.

5. **Heterogeneidad y centrado**
   (a) Estima \(Y \sim D \times \text{mujer}\) y reporta `margins`.
   (b) Estima \(Y \sim D \times \text{libros}\) **sin centrar** y **con centrado**. Compara el coeficiente de \(D\) en ambos casos.
   (c) Grafica `marginsplot` para libros y comenta el perfil.

**Bonus (opcional):**
6\. Repite la estimación con **SE cluster** por `semestre`. Discute diferencias con SE robustas (nota: con solo 4 clusters, ¿qué problema surge?).
:::



---

::: {.boxvideo .green title="Videos recomendados:"}

- [Video 1](https://www.youtube.com/embed/eGRd8jBdNYg)
- [Video 2](https://www.youtube.com/embed/crpuBZv6XtA)
- [Video 3](https://www.youtube.com/embed/xlX3VtuIfQ0)

Y todos los que encuentres en Google buscando: **RCT Esther Duflo**
:::

::: {.boxnote}

**PROMPT DE CHATGPT PARA REFLEXIÓN PROFUNDA**

**Instrucciones**: Copia este mensaje en ChatGPT o la IA de tu preferencia. Tu objetivo no es obtener respuestas, sino **reflexionar guiado por preguntas**.

---

Hola. Actúa como mi tutor de Stata para diseño experimental. No quiero que me des código directamente. Quiero que me ayudes a pensar paso a paso.

Tengo un experimento con datos de varios semestres (variable `semestre`). Ya estimé el modelo simple \(Y = \alpha + \tau D + u\). Ahora quiero entender:

Por favor, hazme preguntas como:

- ¿Qué pasa con mi estimador \(\hat{\tau}\) si no incluyo dummies de semestre, sabiendo que la aleatorización fue **dentro** de cada semestre?
- ¿Cómo interpreto el coeficiente de \(D\) cuando interactúo con una variable continua? ¿Qué pasa si no centro?
- Si tengo solo 4 semestres y quiero hacer cluster SE por semestre, ¿cuántos clusters necesito para que los SE sean confiables?
- ¿Por qué el \(R^2\) sube al agregar estratos pero \(\hat{\tau}\) casi no cambia?

No me des respuestas. Solo nuevas preguntas que me ayuden a entender mejor la conexión entre diseño y estimación.

:::

---
